### ISSUE TITLE
[META ISSUE]: BBB v3.0 - Apollo GraphQL integration

### ISSUE THREAD

**Issue by frankemax** [mconf/bbb-mobile-sdk#861]
Meteor
--
- [x] #862

Join
--
- [x] #864
```
requestSessionToken();
joinWithSessionToken();
callApiEnter();
connectGraphqlServer();
```
- [x] #868
- [x] #912

Review cases:
--
### Leave session
- [x] Leave Session: review user leave
- [x] Leave Session: refresh/clean store

### Reconnect
- [x] Reconnect: review

### Whiteboard webview:
- [x] Whiteboard webview: review live code

Review Middlewares:
--
### Connection status
- [x] Connection status: review middleware

### Login
- [x] Login middleware: join audio on login

### Logout
- [x] Logout middleware: logout/ejection observer

Review Screens:
--

### Main conference screen
- [x] #872
- [x] #874
- [x] #877
- [x] #928
- [x] #914
- [x] #933
- [x] Main screen: review mini audio player icon
- [x] Main screen: review PiP
- [x] #988 --> moved to another release

### Screen wrapper
- [x] #876
- [x] #885
- [x] #931
- [x] #929
- [x] #878
- [x] #884
- [x] #880

### Fullscreen wrapper screen
- [ ] Fullscreen wrapper: use Apollo client stuff

### Guest screen
- [x] #869

###  Inside breakout screen
- [x] #901

### Breakout room list screen
- [x] #900
- [x] #904
- [x] #921

### Poll screen
- [x] #895
- [x] #894
- [x] #905
- [x] #906
- [x] #916
- [x] #917

### Language screen
- [x] Language screen: use Apollo client stuff

### Drawer navigator screen
- [x] #886
- [x] #911

### User notes screen
- [x] #890
- [x] User notes screen: review webview behaviour 

### User participants screen
- [x] #875
- [x] #882
- [x] #883
- [x] #896
- [x] #897
- [x] #898

### Transfer screen ?
- [x] Transfer screen: use Apollo client stuff

### End session screen
- [x] #907
- [x] #981
- [x] End session screen: review useEndReason hook

### Feedback screen
- [x] #989
  - [x] Feedback screen: use Apollo client stuff
  - [x] Feedback screen: review email-feedback screen
  - [x] Feedback screen: review problem-feedback screen
  - [x] Feedback screen: review specific-feedback screen

**Comment by matheus-lagreca** [comment]
Clean up this issue, and create a part 2 for fixes and stuff that was missing in version 0.16.z
